config/routes.rb
DigitalIsland::Application.routes.draw do

  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]
  resources :items

  root :to => 'usuarios#index'

  match '/registro', to: 'usuarios#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id           :integer         not null, primary key
#  usuario_id   :integer
#  detalle      :string(255)
#  reporte      :string(255)
#  estado       :string(255)
#  created_at   :datetime        not null
#  updated_at   :datetime        not null
#  recogido_por :string(255)
#  ac           :integer
#  total        :integer
#

class Item < ActiveRecord::Base
  attr_accessible :detalle, :estado, :reporte, :recogido_por, :ac, :trabajo, :repuesto, :tecnico
  belongs_to :usuario

  before_validation :cuentas_to_i
  before_save :calc_total


  validates :usuario_id,  presence: true

  validates :detalle,     presence: true,
                          length: { maximum: 250 }

  validates :estado,      presence: true

  validates :reporte,     length: { maximum: 2000 }

  validates :recogido_por,  length: { maximum: 50 }

  validates :ac,          numericality: { only_integer: true, 
                                          greater_than_or_equal_to: 0 },
                          length: { maximum: 5 }              

  validates :total,       numericality: { only_integer: true, 
                                          greater_than_or_equal_to: 0 },
                          length: { maximum: 5 }              

  validates :trabajo,     numericality: { only_integer: true, 
                                          greater_than_or_equal_to: 0 },
                          length: { maximum: 5 }              

  validates :repuesto,    numericality: { only_integer: true, 
                                          greater_than_or_equal_to: 0 },
                          length: { maximum: 5 }              

  validates :tecnico,     length: { maximum: 50 }


  default_scope order: 'items.created_at DESC'



private
  
  def cuentas_to_i
    self.ac = ac.to_i
    self.total = total.to_i
    self.trabajo = trabajo.to_i
    self.repuesto = repuesto.to_i
  end

  def calc_total
    self.total = self.trabajo + self.repuesto
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :logear_usuario
  before_filter :no_cliente, only: [:index, :new, :create, :edit, :update, :destroy]
  before_filter :solo_admin, only: :destroy

  def index
    @items = Item.all
  end

  def new
    @cliente = Usuario.find(session[:cliente])
    @item = @cliente.items.build()
  end

  def create
    @cliente = Usuario.find(session[:cliente])
    @item = @cliente.items.build(params[:item])
    @item.estado = 'recibido'
    if @item.save
      flash[:notice] = "item creado"
      redirect_to @cliente
    else
      flash.now[:error] = "#{params}"
      render :new
    end
  end

  def show
    @item = Item.find_by_id(params[:id])
  end

  def edit
    @item = Item.find_by_id(params[:id])
  end

  def update
    @item = Item.find_by_id(params[:id])
    if @item.update_attributes(params[:item])
      flash[:success] = "Item actualizado"
      redirect_to @item
    else
      flash.now[:error] = "Datos invalidos"
      render :edit
    end
  end

  def destroy
    @item = Item.find_by_id(params[:id])
    @item.destroy
    flash[:success] = "Item Deleted"
    redirect_to items_path
  end
end

private
  
  def solo_admin
    redirect_to items_path , notice: "No no no!" unless current_user.admin?
  end

app/helpers/items_helper.rb
module ItemsHelper

  def tecnicos
    tecnicos ||= Usuario.where("tecnico = ?",true)
    ( tecnicos.respond_to?(:map) ) ? tecnicos.map { |tecnico| tecnico.nombre_completo } : tecnico.nombre_completo
  end


end

private
  
  estados = ['recibido', 'revisado', 'listo', 'recogido']

app/views/items/_item.html.erb
<tr>
  <td><%= item.id %></td>
  <td><%= link_to "#{item.detalle[0..20]}", item %></td>
  <td><%= item.estado %></td>

  <% unless current_user.cliente? %>
  <td><%= link_to "#{item.usuario.nombre_completo}", item.usuario%></td>
  <td><%= item.tecnico %></td>
  <% end -%>

  <td><%= item.created_at.localtime.strftime("%d-%m-%y") %></td>
  <td><%= item.updated_at.localtime.strftime("%d-%m-%y") if item.estado == 'entregado' %></td>


  <td><%= "#{item.ac}" unless item.ac.nil? %></td>
  <td><%= "#{item.trabajo}" unless item.ac.nil? %></td>
  <td><%= "#{item.repuesto}" unless item.ac.nil? %></td>
  <td><%= "#{item.total}" unless item.total.nil? %></td>


  <% if current_user.admin? %>
  <td><%= link_to "delete", item, method: :delete,
                                  confirm: "Seguro??" %></td>
  <% end -%>
</tr>

app/views/items/edit.html.erb
<div class="row">
  
  <div class="span8 offset2">
    <h1>Editar Item # <%= @item.id %></h1>

    <%= form_for(@item, html: { class: "form-horizontal" })  do |f| -%>
    <fieldset>

      <% if current_user.tecnico? %>

        <div class="control-group">
            <%= f.label :detalle, class: "control-label" %>
          <div class="controls">
            <%= f.text_area :detalle , rows: "8", readonly: "readonly"%>
          </div>
        </div>

        <div class="control-group">
            <%= f.label :reporte, class: "control-label" %>
          <div class="controls">
            <%= f.text_area :reporte , rows: "8"%>
          </div>
        </div>

        <div class="control-group">
            <%= f.label :tecnico, class: "control-label" %>
          <div class="controls">

            <% tecnicos.each do |n| %>
              <label class="radio">
                <%= f.radio_button :tecnico, "#{n}" %>
                <%= "#{n}" %>
              </label>
            <% end -%>
            
          </div>
        </div>
      <% end -%>

        <div class="control-group">
            <%= f.label :estado, class: "control-label" %>
          <div class="controls">

            <% if current_user.tecnico? %>
              <label class="radio">
                <%= f.radio_button :estado, "revisado" %>
                Revisado
              </label>
              <label class="radio">
                <%= f.radio_button :estado, "listo" %>
                Listo
              </label>
            <% end -%>
            
            <label class="radio">
              <%= f.radio_button :estado, "entregado" %>
              Entregar
            </label>
          </div>
        </div>

        <div class="control-group">
           <%= f.label :repuesto, class: "control-label" %>
          <div class="controls">
            <%= f.number_field :repuesto , class: "span2" %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :trabajo, class: "control-label" %>
          <div class="controls">
            <%= f.number_field :trabajo , class: "span2"%> 
          </div>
        </div>

        <div class="control-group">
          <%= f.label :recogido_por, "Recogio" , class: "control-label"%>
          <div class="controls">
            <%= f.text_field :recogido_por %>
            <p class="help-block"> Si el que esta recogiendo es otra persona q el cliente </p>
          </div>
        </div>

      
      <div class="form-actions">
        <%= f.submit "Guardar", class: "btn btn-primary" %>
        <%= link_to "Cancelar", root_path, class: "btn" %>
      </div>      
    </fieldset>
    <% end -%>
  </div>
</div>

app/views/items/index.html.erb
<div class="row">
  <div class="span12">
    <h1>Items</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Detalle</th>
          <th>Estado</th>
          <th>Cliente</th>
          <th>Tecnico</th>
          <th>Recibido</th>
          <th>Entregado</th>
          <th>a/c</th>
          <th>trabajo</th>
          <th>repuesto</th>
          <th>Total</th>

        </tr>
      </thead>
      <tbody>
        <%= render @items %>
      </tbody>
    </table>

  </div>
</div>

app/views/items/new.html.erb
<div class="row">
  
  <div class="span6 offset3">
    <h1>Nuevo Item</h1> 

    <%= form_for(@item, html: { class: "form-horizontal" })  do |f| -%>
    <fieldset>
      <div class="control-group">
          <%= f.label :detalle, class: "control-label" %>
        <div class="controls">
          <%= f.text_area :detalle , rows: "10"%>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :ac, "a/c",  class: "control-label" %>
        <div class="controls">
          <%= f.number_field :ac , class: "span2"%> 
        </div>
      </div>

        <div class="control-group">
        <%= f.label :trabajo,  class: "control-label" %>
        <div class="controls">
          <%= f.number_field :trabajo , class: "span2"%> 
        </div>
      </div>
      
      <div class="form-actions">
        <%= f.submit "Guardar", class: "btn btn-primary" %>
        <%= link_to "Cancelar", root_path, class: "btn" %>
      </div>      
    </fieldset>
    <% end -%>
  </div>
</div>

app/views/items/show.html.erb
<div class="row">
  <aside class="span4">
      <h1># <%= @item.id %></h1>
    <section>

      <div id="estado">
        <p>
          <strong><%= @item.estado %></strong>
        </p>

        <% if current_user.tecnico? %>
          <p>
            <%= link_to "REPORTE", edit_item_path(@item), class: "btn btn-primary" %>
          </p>
        <% end -%>

        <% if current_user.vendedor? %>
          <p>
            <%= link_to "ENTREGAR", edit_item_path(@item), class: "btn btn-primary" %>
          </p>
        <% end -%>

      </div>
    </section>
    
  </aside>

  <div id="descripcion" class="span8">
    
    <h3>Descripcion</h3>

    <div class="row item-descripcion">
      <div class="span1 der"><strong>Nombre</strong></div>
      <div class="span4">
          <%= link_to @item.usuario.nombre+' '+@item.usuario.apellido, @item.usuario %>
      </div>
    </div>  
   
    <div class="row item-descripcion">
      <div class="span1 der"><strong>Detalle</strong></div>
      <div class="span4">
          <textarea name="detalle"  cols="30" rows="8" readonly="readonly"><%= @item.detalle %></textarea>
      </div>
    </div>

    <% unless @item.reporte.nil? %>
    <div class="row item-descripcion">
      <div class="span1 der"><strong>Reporte</strong></div>
      <div class="span4">
          <textarea name="detalle"  cols="30" rows="8" readonly="readonly"><%= @item.reporte %></textarea>
      </div>
    </div>
    <% end -%>

  </div>  

</div>