config/routes.rb
DigitalIsland::Application.routes.draw do

  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]
  resources :items

  root :to => 'usuarios#index'

  match '/registro', to: 'usuarios#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete

end

app/models/usuario.rb
# == Schema Information
#
# Table name: usuarios
#
#  id              :integer         not null, primary key
#  nombre          :string(255)
#  apellido        :string(255)
#  email           :string(255)
#  telefono        :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean         default(FALSE)
#  tecnico         :boolean         default(FALSE)
#  vendedor        :boolean         default(FALSE)
#  cliente         :boolean         default(TRUE)
#  created_by      :string(255)
#

class Usuario < ActiveRecord::Base
  attr_accessible :apellido, :email, :nombre, :telefono, :password, :password_confirmation
  has_secure_password
  has_many :items, dependent: :destroy

  before_save :create_remember_token
  before_save :titleize_nombre
  before_save { |user| user.email = email.downcase }
  # before_save :registrar_created_by

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_TELEFONO_REGEX = /^([0-9\-\s])*$/


  validates :nombre,    presence: true,
                        length: { maximum: 50 }

  validates :apellido,  presence: true,
                        length: { maximum: 50 }

  validates :email,     presence: true,
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }

  validates :telefono,  presence: true,
                        length: { maximum: 23 },
                        format: { with: VALID_TELEFONO_REGEX }

  validates :password,  presence: true,
                        length: { minimum: 6 },
                        on: :create
                        
  validates :password_confirmation,  presence: true,
                                     on: :create


  def nombre_completo
    "#{nombre} #{apellido}"
  end


  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    def titleize_nombre
      self.nombre = nombre.titleize
      self.apellido = apellido.titleize
    end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_filter :logear_usuario
  # before_filter :usuario_actual, only: [:edit, :update]
  before_filter :usuario_correcto, only: [:show ,:edit, :update]
  before_filter :registro_clientes, only: [:new, :create]
  before_filter :no_cliente, only: :index
  before_filter :admin_user, only: :destroy

  
  
  def index
    @title = "Usuarios"
    @usuarios = Usuario.all
  end

  def new
    @title = "Registro"
    @usuario = Usuario.new()
  end

  def show
    # @usuario = Usuario.find(params[:id])
    @title = @usuario.nombre
    @items = @usuario.items
    session[:cliente] = @usuario.id
  end

  def create
    @usuario = Usuario.new(params[:usuario])
    @usuario.password = DEFAULT_PASSWORD
    @usuario.password_confirmation = DEFAULT_PASSWORD
    @usuario.created_by = current_user.nombre
    if @usuario.save
      flash[:success] = "Usuario creado correctamente"
      redirect_to @usuario
    else
      @title = "Registro"
      flash.now[:error] = "Revisa los datos"
      render :new
    end
  end

  def edit
    # @usuario = Usuario.find_by_id(params[:id])
    # @title = "Editar perfil de #{@usuario.nombre}"
  end

  def update
    # @usuario = Usuario.find_by_id(params[:id])
    # @usuario.nombre = params[:usuario][:nombre]
    # @usuario.apellido = params[:usuario][:apellido]
    # @usuario.email = params[:usuario][:email]
    # @usuario.telefono = params[:usuario][:telefono]

    if @usuario.update_attributes(params[:usuario])
      flash[:success] = "Datos actualizados"
      if current_user.cliente?
        log_in @usuario
        redirect_to @usuario
      else
        log_in @usuario if current_user?(@usuario)
        redirect_to root_path
      end
    else
      flash.now[:error] = "Datos invalidos"
      @title = "Editar"
      render :edit
    end

  end

  def destroy
    Usuario.find(params[:id]).destroy
    flash[:success] = "usuario eliminado"
    redirect_to root_path
  end
end

private




  def registro_clientes 
    redirect_to root_path, notice: "Acceso restringido" if current_user.cliente?
  end

  def usuario_correcto
    @usuario = Usuario.find_by_id(params[:id])
    @title = "Editar perfil de #{@usuario.nombre}"
    if current_user.cliente?
      redirect_to(root_path) unless current_user?(@usuario)
    end
  end

  

  def admin_user
    redirect_to root_path unless current_user.admin? 
  end

app/helpers/usuarios_helper.rb
module UsuariosHelper

  def rol(usuario)
    return "cliente" if usuario.cliente?
    return "vendedor" if usuario.vendedor?
    return "tecnico" if usuario.tecnico?
  end
end

app/views/usuarios/_form_for_fields.html.erb
<%= f.label :nombre %>
<%= f.text_field :nombre %>

<%= f.label :apellido %>
<%= f.text_field :apellido %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :telefono %>
<%= f.text_field :telefono %>

app/views/usuarios/_form_for_password.html.erb
<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirmar Password" %>
<%= f.password_field :password_confirmation %>

app/views/usuarios/edit.html.erb
<h1>
  Editar
</h1>

      
      

<div class="row">
  <div class="span6 offset3">
    
    <%= form_for @usuario do |f| -%>
      
      <%= render 'form_for_fields', f: f %>

    
      <%= render 'form_for_password', f: f %>
      
      <%= f.submit "Guardar datos", class: "btn btn-large btn-danger" %>
      <%= link_to "Cancelar", root_path, class: "btn btn-large" %>

    <% end -%>


    

  </div>
</div>

app/views/usuarios/index.html.erb
<h1>
  Lista de los Usuarios
</h1>

<div class="users">
  
  <table id="usuarios" class="table table-striped">

    <thead>
      <tr>
        <th>Nombre</th>
        <th>Telefono</th>
        <th>Email</th>
        <th>Permiso</th>

      </tr>
    </thead>
    <tbody>
      <% @usuarios.each do |usuario| %>
        <% unless current_user == usuario || usuario.admin? %>
          <tr>
            <td><%= link_to "#{usuario.nombre_completo}", usuario %></td>
            <td><%= usuario.telefono %></td>
            <td><%= usuario.email %></td>
            <td><%= rol(usuario)  %></td>
            <% if current_user.admin? %>
            <td><%= usuario.created_by%></td>
            <td><%= usuario.created_at.strftime("%d-%m-%Y")%></td>
            <td><%= link_to 'delete', usuario, method: 'delete', confirm: "Estas seguro??" %></td>
            <% end -%>
          </tr>
        <% end -%>
      <% end -%>
    </tbody>


  </table>


</div>

app/views/usuarios/new.html.erb
<h1>Registro</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @usuario do |f| -%>

      <%= f.label :nombre %>
      <%= f.text_field :nombre %>

      <%= f.label :apellido %>
      <%= f.text_field :apellido %>
      
      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :telefono %>
      <%= f.text_field :telefono %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>
      
      <%= f.label :password_confirmation, "Confirmar Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Crear cuenta",  class: "btn btn-large btn-danger" %>      
      
    <% end -%>
  </div>
</div>

app/views/usuarios/show.html.erb
<div class="row">
  <aside class="span3">
    <section>
      <h1>
        <%= @usuario.nombre %> 
      </h1>
  
      <div id="datos">
        <p>
          <strong>Telf: </strong><%= @usuario.telefono %> 
        </p>
        <p>
          <%= @usuario.email %> 
        </p>
        <% if current_user?(@usuario) %>
        <%= link_to "EDITAR DATOS", edit_usuario_path(@usuario), class: "btn btn-small btn-info"%>
        <% end -%>

        <% if current_user.tecnico || current_user.vendedor? %>
        <p>
          <%= link_to "NUEVO ITEM", new_item_path, class: "btn btn-small btn-primary" %>
        </p>
        <% end -%>
      </div>
    </section>
  </aside>

  <div class="span9">
    
    <% if @usuario.items.any? %>
      <h3>Items</h3>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>#N</th>
            <th>Detalle</th>
            <th>Estado</th>
            <% unless current_user.cliente? %>
            <th>Cliente</th>
            <th>Tecnico</th>
            <% end -%>
            <th>Recibido</th>
            <th>Entregado</th>
            <th>a/c</th>
            <th>Trabajo</th>
            <th>Extra</th>
            <th>Total</th>
            <th></th>

         </tr>
        </thead>
        <tbody>
        
          <%= render @items %>

        </tbody>
      </table>
    <% end -%>
  </div>
</div>