config/routes.rb
DigitalIsland::Application.routes.draw do

  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]
  resources :items

  root :to => 'usuarios#index'

  match '/registro', to: 'usuarios#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
    <ul>
      
      <li><%= link_to "Privace", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "Ayuda", '#' %></li>

    </ul>
  </nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Digital Island", root_path, id: "logo", class: "brand" %>
      <nav>
        <ul class="nav">
          <li><a id="telefono">Esteban Arce 1496 | TELF: 4550259</a></li>
        </ul>

        <ul class="nav pull-right">
          <% if loged_in? %>

            <% unless current_user.cliente? %>
              <li> <%=  link_to "Registrar cliente", registro_path  %> </li>
              <li><%= link_to "Clientes", usuarios_path %></li>
              <li><%= link_to "Items", items_path %></li>
            <% end -%>
            

            <li> <%= link_to current_user.nombre, current_user %> </li>
            <li> <%= link_to "Salir", logout_path, method: 'delete' %> </li>
          <% else %>
            <li><%= link_to "Entrar", login_path %></li>
          <% end -%>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(@title) %> </title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    
    <%= render 'layouts/header' %>

    <div class="container">

      <% flash.each do |key, value| %>
        <!-- <div class="alert alert-<%= key %>"><%= value %></div> -->
        <%= content_tag(:div, value, class: "alert alert-#{key}" ) %>
      <% end -%>

      <%= yield %>

    <%= render 'layouts/footer' %>

    <%= debug(params) if Rails.env.development? %>
    </div>


  </body>
</html>